const classData = [
  {
    id: 1,
    className: "UI/UX Designing",
    staffName: "Surya R",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "surya.jpg",
    classTime: "2024-08-09T10:10:00",
  },
  {
    id: 2,
    className: "Graphic Designing",
    staffName: "Priya Sweety",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "priya.jpg",
    classTime: "2024-08-09T09:51:00",
  },
  {
    id: 3,
    className: "Design Hierarchy",
    staffName: "Leslie Alexander",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "leslie.jpg",
    classTime: "2024-08-09T00:30:00",
  },
  {
    id: 4,
    className: "Basics of Frontend",
    staffName: "Courtney Henry",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "courtney.jpg",
    classTime: "2024-08-09T00:45:00",
  },
  {
    id: 5,
    className: "Graphic Designing",
    staffName: "Jerome Bell",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "jerome.jpg",
    classTime: "2024-08-09T01:00:00",
  },
  {
    id: 6,
    className: "Graphic Designing",
    staffName: "Arlene McCoy",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "arlene.jpg",
    classTime: "2024-08-09T01:15:00",
  },
  {
    id: 7,
    className: "Graphic Designing",
    staffName: "Arlene McCoy",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "arlene.jpg",
    classTime: "2024-08-09T01:30:00",
  },
  {
    id: 8,
    className: "Graphic Designing",
    staffName: "Arlene McCoy",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "arlene.jpg",
    classTime: "2024-08-09T01:45:00",
  },
  {
    id: 9,
    className: "Graphic Designing",
    staffName: "Arlene McCoy",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "arlene.jpg",
    classTime: "2024-08-09T09:40:00",
  },
  {
    id: 10,
    className: "Graphic Designing",
    staffName: "Arlene McCoy",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "arlene.jpg",
    classTime: "2024-08-09T10:32:00",
  },
];

export default classData;
