const classData = [
  {
    id: 1,
    className: "UI/UX Designing",
    staffName: "Surya R",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "https://randomuser.me/api/portraits/men/1.jpg",
    classTime: new Date(Date.now() + 60 * 1000),
  },
  {
    id: 2,
    className: "Graphic Designing",
    staffName: "Priya Sweety",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "https://randomuser.me/api/portraits/women/1.jpg",
    classTime: new Date(Date.now() + 160 * 1000),
  },
  {
    id: 3,
    className: "Design Hierarchy",
    staffName: "Leslie Alexander",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "https://randomuser.me/api/portraits/men/2.jpg",
    classTime: new Date(Date.now() + 120 * 1000),
  },
  {
    id: 4,
    className: "Web Development",
    staffName: "John Doe",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "https://randomuser.me/api/portraits/men/3.jpg",
    classTime: "2024-08-10T14:00:00",
  },
  {
    id: 5,
    className: "Frontend Basics",
    staffName: "Jane Smith",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "https://randomuser.me/api/portraits/women/2.jpg",
    classTime: "2024-08-10T08:45:00",
  },
  {
    id: 6,
    className: "Backend Development",
    staffName: "Michael Johnson",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "https://randomuser.me/api/portraits/men/4.jpg",
    classTime: new Date(Date.now() + 180 * 1000),
  },
  {
    id: 7,
    className: "React.js Essentials",
    staffName: "Emily Davis",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "https://randomuser.me/api/portraits/women/3.jpg",
    classTime: "2024-08-11T16:00:00",
  },
  {
    id: 8,
    className: "Node.js for Beginners",
    staffName: "Robert Brown",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "https://randomuser.me/api/portraits/men/5.jpg",
    classTime: new Date(Date.now() + 220 * 1000),
  },
  {
    id: 9,
    className: "JavaScript Advanced",
    staffName: "Olivia Wilson",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "https://randomuser.me/api/portraits/women/4.jpg",
    classTime: new Date(Date.now() + 360 * 1000),
  },
  {
    id: 10,
    className: "HTML & CSS",
    staffName: "Liam Martinez",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "https://randomuser.me/api/portraits/men/6.jpg",
    classTime: "2024-08-13T15:00:00",
  },
  {
    id: 11,
    className: "Vue.js for Beginners",
    staffName: "Sophia Anderson",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "https://randomuser.me/api/portraits/women/5.jpg",
    classTime: "2024-08-13T18:30:00",
  },
  {
    id: 12,
    className: "Fullstack Development",
    staffName: "Benjamin Thomas",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "https://randomuser.me/api/portraits/men/7.jpg",
    classTime: "2024-08-14T11:30:00",
  },
  {
    id: 13,
    className: "Angular Basics",
    staffName: "Charlotte Lee",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "https://randomuser.me/api/portraits/women/6.jpg",
    classTime: "2024-08-14T13:45:00",
  },
  {
    id: 14,
    className: "Python Programming",
    staffName: "David White",
    isBooked: false,
    timerEndTime: 0,
    timeRemaining: 0,
    isLive: false,
    classStartTime: 0,
    timeLive: 0,
    staffImage: "https://randomuser.me/api/portraits/men/8.jpg",
    classTime: "2024-08-15T09:15:00",
  },

];
export default classData;
